# Generated by Django 5.0.1 on 2024-01-12 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
