# Generated by Django 5.0.1 on 2024-01-15 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0003_alter_favorite_study_program_alter_link_link_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='status',
            field=models.CharField(choices=[('interested', 'interested'), ('applied', 'applied'), ('accepted', 'accepted'), ('waitlisted', 'waitlisted'), ('enrolled', 'enrolled')], help_text="The status of the student's application, if they apply."),
        ),
    ]
