# Generated by Django 5.0.1 on 2024-01-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='username'),
        ),
    ]
