# Generated by Django 5.0.1 on 2024-01-19 11:05

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0006_alter_user_managers_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyprogram',
            name='discipline',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='insertion_rate',
        ),
        migrations.RemoveField(
            model_name='studyprogram',
            name='insertion_time_period',
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='L1_success_rate_quartile',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='The quartile in which the percentage of students who continue to L2 falls compared to all programs', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='acceptance_rate_quartile',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='The quartile in which the acceptance rate falls compared to all programs', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='available_places',
            field=models.PositiveIntegerField(blank=True, help_text='The number of students who can enroll in the program.', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='city',
            field=models.CharField(blank=True, help_text='City in which the program is located.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='diploma_earned_ontime',
            field=models.FloatField(blank=True, help_text="The percentage of students who complete the program within 3-4 years for a 'licence' or 2-3 years.", null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='diploma_earned_ontime_quartile',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='The quartile in which the percentage of students who graduate on time falls compared to all programs', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Longitude and latitude of the program location.', null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='is_selective',
            field=models.BooleanField(blank=True, help_text='True if the program is selective, false if it is non-selective.', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='job_prospects',
            field=models.TextField(blank=True, help_text="The job prospects of the program's graduates scraped from the parcoursup website.", null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='number_applicants',
            field=models.PositiveIntegerField(blank=True, help_text='The number of students who applied to the program.', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='out_of_sector_candidates',
            field=models.FloatField(blank=True, help_text="The percentage of students from outside of the program's area who are admitted to the program.", null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='percent_scholarship',
            field=models.FloatField(blank=True, help_text='The percentage of students who receive a government scholarship (boursiers).', null=True),
        ),
        migrations.AddField(
            model_name='studyprogram',
            name='percent_scholarship_quartile',
            field=models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], help_text='The quartile in which the percentage of scholarship studentsfalls compared to all programs', null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='geolocation',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text="Longitude and latitude of the address's location.", null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='acceptance_rate',
            field=models.FloatField(blank=True, help_text='The percentage of applicants who are admitted to the program via parcoursup.', null=True),
        ),
        migrations.AlterField(
            model_name='studyprogram',
            name='description',
            field=models.TextField(blank=True, help_text='The description of the program scraped from the parcoursup website.', null=True),
        ),
    ]
