# Generated by Django 5.0.1 on 2024-01-19 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("private_app", "0007_remove_studyprogram_discipline_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studyprogram",
            name="city",
        ),
        migrations.RemoveField(
            model_name="studyprogram",
            name="geolocation",
        ),
        migrations.AddField(
            model_name="studyprogram",
            name="address",
            field=models.OneToOneField(
                blank=True,
                null=True,
                help_text="The study program's city and GPS location.",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="study_program",
                to="private_app.address",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="address",
            name="locality",
            field=models.CharField(
                blank=True,
                help_text="The city and more precise locality info (as required) for the address.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postcode",
            field=models.PositiveIntegerField(
                blank=True, help_text="Post code for the address.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="street_address",
            field=models.CharField(
                blank=True,
                help_text="Building number and street name of the address.",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="school",
            name="name",
            field=models.CharField(
                help_text="The name of the school or university.", max_length=150
            ),
        ),
        migrations.AlterField(
            model_name="studyprogram",
            name="name",
            field=models.CharField(
                help_text="The name of the program of study.", max_length=150
            ),
        ),
    ]
