# Generated by Django 5.0.1 on 2024-01-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0008_remove_studyprogram_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='name',
            field=models.CharField(help_text='The name of the program of study.', max_length=250),
        ),
    ]
