# Generated by Django 5.0.1 on 2024-01-31 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0009_alter_studyprogram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studyprogram',
            name='name',
            field=models.CharField(help_text='The name of the program of study.', max_length=300),
        ),
    ]
