# Generated by Django 5.0.1 on 2024-02-08 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('private_app', '0010_alter_studyprogram_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_url',
            field=models.OneToOneField(blank=True, help_text="A url to the school's website.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='school', to='private_app.link'),
        ),
    ]
